#!/bin/sh

export TEMP_DIR="$(mktemp -d)"

if [ ! -f "${OPENVPN_CONFIG_FILE}" ] ; then
    echo "No OpenVPN config. Exiting."
    exit 1
fi

# Add ovpn user/pass
if ! [ -z ${OPENVPN_USERNAME} ]; then
    # https://stackoverflow.com/questions/38869427/openvpn-on-linux-passing-username-and-password-in-command-line
    sudo bash -c "openvpn --config ${OPENVPN_CONFIG_FILE} --auth-user-pass <(echo -e "$OPENVPN_USERNAME\\\\n$OPENVPN_PASSWORD")"
else
    sudo openvpn --config "${OPENVPN_CONFIG_FILE}"
fi
