#!/bin/sh

export TEMP_DIR="$(mktemp -d)"

if [ ! -f "${OPENVPN_CONFIG_FILE}" ] ; then
    echo "No OpenVPN config. Exiting."
    exit 1
fi


if [ ! -f "${TEMP_DIR}/config.ovpn" ]; then
    cp "${OPENVPN_CONFIG_FILE}" "${TEMP_DIR}/config.ovpn"
fi

# Add ovpn user/pass
if ! [ -z ${OPENVPN_USERNAME} ]; then
    # https://stackoverflow.com/questions/38869427/openvpn-on-linux-passing-username-and-password-in-command-line
    if ! openvpn --config "${TEMP_DIR}/config.ovpn" --auth-user-pass <(echo -e "$OPENVPN_USERNAME\\n$OPENVPN_PASSWORD"); then
        exit_code=$?
        echo "OpenVPN failed"
        sleep 5
        exit $exit_code
    fi
else
    if ! openvpn --config "${TEMP_DIR}/config.ovpn"; then
        exit_code=$?
        echo "OpenVPN failed"
        sleep 5
        exit $exit_code
    fi
fi
