#!/bin/sh

export TEMP_DIR="$(mktemp -d)"

if [ ! -f "${OPENVPN_CONFIG_FILE}" ] ; then
    echo "No OpenVPN config. Exiting."
    exit 1
fi


if [ ! -f "${TEMP_DIR}/config.ovpn" ]; then
    cp "${OPENVPN_CONFIG_FILE}" "${TEMP_DIR}/config.ovpn"
fi

TARGET_CIPHER="$(cat "${OPENVPN_CONFIG_FILE}" | grep "^cipher" | rev | cut -d ' ' -f1 | rev | tr -d ' ' | tr -d '\r' | tr -d '\n')"

# Add ovpn user/pass
if ! [ -z ${OPENVPN_USERNAME} ]; then
    # https://stackoverflow.com/questions/38869427/openvpn-on-linux-passing-username-and-password-in-command-line
    sudo bash -c "openvpn --config ${TEMP_DIR}/config.ovpn --auth-user-pass <(echo -e "$OPENVPN_USERNAME\\\\n$OPENVPN_PASSWORD")"
else
    sudo openvpn --config
fi
